version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.12
    working_directory: ~/repo

    steps:
      - checkout
      - run: make test
      - store_artifacts:
          path: coverage
          prefix: coverage
